# Generated by Django 4.2.7 on 2024-07-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
