# Generated by Django 4.2.13 on 2024-09-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
